<?php 
require_once '../../config.php';
require_once '../../db/conexion.php';
require '../../vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Borders;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Conditional;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Style\Protection;
use PhpOffice\PhpSpreadsheet\Style\Style;
use PhpOffice\PhpSpreadsheet\Style\Supervisor;


$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
//Titulos
$sheet->setCellValue('A5', 'DATOS DE IDENTIFICACIÓN');
$sheet->mergeCells('A5:I5');
$sheet->setCellValue('J5', 'MODALIDAD DE SUMINISTRO');
$sheet->mergeCells('J5:K5');
$sheet->setCellValue('L5', 'CONCEPTO SANITARIO');
$sheet->mergeCells('L5:N5');
	$sheet->setCellValue('A6', 'NOMBRE DE LA ETC');
	$sheet->mergeCells('A6:A9');
	$sheet->setCellValue('B6', 'CÓDIGO DANE DEL MUNICIPIO');
	$sheet->mergeCells('B6:B9');
	$sheet->setCellValue('C6', 'NOMBRE DEL MUNICIPIO');
	$sheet->mergeCells('C6:C9');
	$sheet->setCellValue('D6', 'CÓDIGO DANE DEL ESTABLECIMIENTO EDUCATIVO');
	$sheet->mergeCells('D6:D9');
	$sheet->setCellValue('E6', 'NOMBRE DEL ESTABLECIMIENTO EDUCATIVO');
	$sheet->mergeCells('E6:E9');
	$sheet->setCellValue('F6', 'CÓDIGO DANE DE LA SEDE');
	$sheet->mergeCells('F6:F9');
	$sheet->setCellValue('G6', 'SEDE EDUCATIVA');
	$sheet->mergeCells('G6:G9');
	$sheet->setCellValue('H6', 'RURAL/URBANA');
	$sheet->mergeCells('H6:H9');
	$sheet->setCellValue('I6', 'ATENCIÓN A POBLACIÓN MAYORITARIAMENTE INDIGENA');
	$sheet->mergeCells('I6:I9');
	$sheet->setCellValue('J6', 'COMPLEMENTO JM/JT');
	$sheet->mergeCells('J6:J9');
	$sheet->setCellValue('K6', 'ALMUERZO');
	$sheet->mergeCells('K6:K9');
	$sheet->setCellValue('L6', 'INSTITUCIÓN EDUCATIVA CUENTA CON COMEDOR ESCOLAR');
	$sheet->mergeCells('L6:L9');
	$sheet->setCellValue('M6', 'CONCEPTO SANITARIO');
	$sheet->mergeCells('M6:M9');
	$sheet->setCellValue('N6', 'FECHA DE EXPEDICIÓN');
	$sheet->mergeCells('N6:N9');


$sheet->setCellValue('O5', 'PARÁMETROS');
$sheet->mergeCells('O5:BN5');
	$sheet->setCellValue('O6', 'ÁREA DE ALMACENAMIENTO');
	$sheet->mergeCells('O6:AC6');
		$sheet->setCellValue('O7', 'MATERIAL EN EL QUE SE ENCUENTRA CONSTRUIDO');
		$sheet->mergeCells('O7:R7');
			$sheet->setCellValue('O8', 'PISO');
			$sheet->mergeCells('O8:O9');
			$sheet->setCellValue('P8', 'PAREDES');
			$sheet->mergeCells('P8:P9');
			$sheet->setCellValue('Q8', 'TECHO');
			$sheet->mergeCells('Q8:Q9');
			$sheet->setCellValue('R8', 'MESONES');
			$sheet->mergeCells('R8:R9');
		$sheet->setCellValue('S7', 'EQUIPOS Y DOTACIÓN');
		$sheet->mergeCells('S7:AC7');
			$sheet->setCellValue('S8', 'NEVERA');
			$sheet->mergeCells('S8:V8');
				$sheet->setCellValue('S9', 'TIENE');
				$sheet->setCellValue('T9', 'EN USO');
				$sheet->setCellValue('U9', 'FUNCIONA');
				$sheet->setCellValue('V9', 'CAPACIDAD');
			$sheet->setCellValue('W8', 'CONGELADOR');
			$sheet->mergeCells('W8:Z8');
				$sheet->setCellValue('W9', 'TIENE');
				$sheet->setCellValue('X9', 'EN USO');
				$sheet->setCellValue('Y9', 'FUNCIONA');
				$sheet->setCellValue('Z9', 'CAPACIDAD');
			$sheet->setCellValue('AA8', 'ESTIBAS');
			$sheet->mergeCells('AA8:AA9');
			$sheet->setCellValue('AB8', 'RECIPIENTES PLÁSTICOS');
			$sheet->mergeCells('AB8:AB9');
			$sheet->setCellValue('AC8', 'CANASTILLAS');
			$sheet->mergeCells('AC8:AC9');
	$sheet->setCellValue('AD6', 'ÁREA DE PREPARACIÓN');
	$sheet->mergeCells('AD6:AR6');
		$sheet->setCellValue('AD7', 'MATERIAL EN EL QUE SE ENCUENTRA CONSTRUIDO');
		$sheet->mergeCells('AD7:AG7');
			$sheet->setCellValue('AD8', 'PISO');
			$sheet->mergeCells('AD8:AD9');
			$sheet->setCellValue('AE8', 'PAREDES');
			$sheet->mergeCells('AE8:AE9');
			$sheet->setCellValue('AF8', 'TECHO');
			$sheet->mergeCells('AF8:AF9');
			$sheet->setCellValue('AG8', 'MESONES');
			$sheet->mergeCells('AG8:AG9');
		$sheet->setCellValue('AH7', 'EQUIPOS Y UTENSILIOS');
		$sheet->mergeCells('AH7:AR7');
			$sheet->setCellValue('AH8', 'ESTUFA');
			$sheet->mergeCells('AH8:AL8');
				$sheet->setCellValue('AH9', 'TIENE');
				$sheet->setCellValue('AI9', 'TIPO');
				$sheet->setCellValue('AJ9', 'EN USO');
				$sheet->setCellValue('AK9', 'FUNCIONA');
				$sheet->setCellValue('AL9', 'CAPACIDAD');
			$sheet->setCellValue('AM8', 'LICUADORA');
			$sheet->mergeCells('AM8:AQ8');
				$sheet->setCellValue('AM9', 'TIENE');
				$sheet->setCellValue('AN9', 'TIPO');
				$sheet->setCellValue('AO9', 'EN USO');
				$sheet->setCellValue('AP9', 'FUNCIONA');
				$sheet->setCellValue('AQ9', 'CAPACIDAD');
			$sheet->setCellValue('AR8', 'CUENTA CON LOS UTENSILIOS SUFICIENTES PARA LA PREPARACION DE LOS ALIMENTOS');
			$sheet->mergeCells('AR8:AR9');
	$sheet->setCellValue('AS6', 'ÁREA DE CONSUMO');
	$sheet->mergeCells('AS6:AY6');
		$sheet->setCellValue('AS7', 'MATERIAL EN EL QUE SE ENCUENTRA CONSTRUIDO');
		$sheet->mergeCells('AS7:AU7');
			$sheet->setCellValue('AS8', 'PISO');
			$sheet->mergeCells('AS8:AS9');
			$sheet->setCellValue('AT8', 'PAREDES');
			$sheet->mergeCells('AT8:AT9');
			$sheet->setCellValue('AU8', 'TECHO');
			$sheet->mergeCells('AU8:AU9');
		$sheet->setCellValue('AV7', 'DOTACION');
		$sheet->mergeCells('AV7:AY7');
			$sheet->setCellValue('AV8', 'MESAS');
			$sheet->mergeCells('AV8:AV9');
			$sheet->setCellValue('AW8', 'SILLAS');
			$sheet->mergeCells('AW8:AW9');
			$sheet->setCellValue('AX8', 'LA CANTIDAD DE MESAS Y SILLAS ES SUFICIENTES PARA LA ATENCIÓN DEL PROGRAMA');
			$sheet->mergeCells('AX8:AX9');
			$sheet->setCellValue('AY8', 'CUENTA CON LOS UTENSILIOS SUFICIENTES PARA EL CONSUMO DE LOS ALIMENTOS');
			$sheet->mergeCells('AY8:AY9');
	$sheet->setCellValue('AZ6', 'SERVICIOS PÚBLICOS');
	$sheet->mergeCells('AZ6:BE6');
	$sheet->setCellValue('BF6', 'MANEJO Y DISPOSICIÓN DE RESIDUOS');
	$sheet->mergeCells('BF6:BH6');
	$sheet->setCellValue('BI6', 'SERVICIOS SANITARIOS');
	$sheet->mergeCells('BI6:BN6');

$writer = new Xlsx($spreadsheet);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Infraestructuras.xlsx"');
$writer->save('php://output','Infraestructuras.xlsx');

 ?>